name: aws-test

on:
  push:
    branches:
      - main

jobs:
  create-file-job:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          echo 'Prajakta' > name.txt
      - name: upload file
        uses: actions/upload-artifact@v4
        with:
          name: prajakta
          path: name.txt

  configure-aws-job:
    needs: create-file-job
    runs-on: ubuntu-latest
    steps:
    - name: remove files
      run: rm -rf name.txt
    - name: download file
      uses: actions/download-artifact@v4
      with:
        name: prajakta
        path: .
    - name: list files
      run: ls -lart
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: US East (N. Virginia) us-east-1
    - name: upload to s3
      run: aws s3 cp name.txt s3://mybucket-12345678900987654321/name.txt
      
